### ISSUE TITLE
No data after 2018-04-02 14:00

### ISSUE THREAD

**Issue by lukaszgryglicki** [igrigorik/gharchive.org#179]
No data after 2018-04-02 14:00
Just try to get:
- `wget http://data.gharchive.org/2018-04-02-15.json.gz`.

While:
- `wget http://data.gharchive.org/2018-04-02-14.json.gz`.

Works OK.
@igrigorik 

All started about (holidays): 2018-04-02 16:18, then 2018-04-02 19:17 and then about 21, 22, 23 it was happenning in all sync attempts:
```
2018-04-02 16:18:15.860904693 +0000 UTC m=+614.559429465: Error result for all (took 3m4.210804779s): exit status 2
2018-04-02 19:17:41.659230579 +0000 UTC m=+580.206503434: Error result for all (took 3m12.081981977s): exit status 2
2018-04-02 21:08:13.156601649 +0000 UTC m=+11.788899054: Error result for kubernetes (took 367.094242ms): exit status 2
2018-04-02 21:08:13.653981742 +0000 UTC m=+12.286279188: Error result for prometheus (took 495.567793ms): exit status 2
2018-04-02 21:08:14.074449974 +0000 UTC m=+12.706747417: Error result for opentracing (took 418.77324ms): exit status 2
2018-04-02 21:08:14.542045062 +0000 UTC m=+13.174342486: Error result for fluentd (took 465.979687ms): exit status 2
2018-04-02 21:08:14.890051061 +0000 UTC m=+13.522348502: Error result for linkerd (took 346.05365ms): exit status 2
2018-04-02 21:08:15.24150894 +0000 UTC m=+13.873806408: Error result for grpc (took 349.5266ms): exit status 2
2018-04-02 21:08:15.582855846 +0000 UTC m=+14.215153314: Error result for coredns (took 339.407408ms): exit status 2
2018-04-02 21:08:15.943040693 +0000 UTC m=+14.575338161: Error result for containerd (took 358.200115ms): exit status 2
2018-04-02 21:08:16.397823651 +0000 UTC m=+15.030121108: Error result for rkt (took 453.000475ms): exit status 2
2018-04-02 21:08:16.733430148 +0000 UTC m=+15.365727586: Error result for cni (took 334.132009ms): exit status 2
2018-04-02 21:08:17.065917472 +0000 UTC m=+15.698214906: Error result for envoy (took 330.631482ms): exit status 2
2018-04-02 21:08:17.500892438 +0000 UTC m=+16.133189829: Error result for jaeger (took 433.191888ms): exit status 2
2018-04-02 21:08:17.851402809 +0000 UTC m=+16.483700238: Error result for notary (took 348.513563ms): exit status 2
2018-04-02 21:08:18.342416363 +0000 UTC m=+16.974713831: Error result for tuf (took 489.666038ms): exit status 2
2018-04-02 21:08:18.732437012 +0000 UTC m=+17.364734470: Error result for rook (took 388.271493ms): exit status 2
2018-04-02 21:08:19.106846838 +0000 UTC m=+17.739144276: Error result for vitess (took 372.5889ms): exit status 2
2018-04-02 21:08:19.473815183 +0000 UTC m=+18.106112644: Error result for nats (took 365.19797ms): exit status 2
2018-04-02 21:08:19.834570315 +0000 UTC m=+18.466867753: Error result for opa (took 359.123394ms): exit status 2
2018-04-02 21:08:20.155612871 +0000 UTC m=+18.787910309: Error result for spiffe (took 319.392349ms): exit status 2
2018-04-02 21:08:20.562715512 +0000 UTC m=+19.195012917: Error result for spire (took 405.505082ms): exit status 2
2018-04-02 21:08:20.839033659 +0000 UTC m=+19.471331065: Error result for opencontainers (took 275.121119ms): exit status 2
2018-04-02 21:08:21.181673099 +0000 UTC m=+19.813970567: Error result for all (took 341.375041ms): exit status 2
2018-04-02 22:08:10.48576674 +0000 UTC m=+9.121991896: Error result for kubernetes (took 333.313131ms): exit status 2
2018-04-02 22:08:10.979287504 +0000 UTC m=+9.615512683: Error result for prometheus (took 492.021665ms): exit status 2
2018-04-02 22:08:11.44218382 +0000 UTC m=+10.078408999: Error result for opentracing (took 461.196921ms): exit status 2
2018-04-02 22:08:11.797755802 +0000 UTC m=+10.433980981: Error result for fluentd (took 353.937541ms): exit status 2
2018-04-02 22:08:12.117059865 +0000 UTC m=+10.753284972: Error result for linkerd (took 317.729936ms): exit status 2
2018-04-02 22:08:12.537037207 +0000 UTC m=+11.173262360: Error result for grpc (took 418.32961ms): exit status 2
2018-04-02 22:08:12.837741029 +0000 UTC m=+11.473966160: Error result for coredns (took 299.186306ms): exit status 2
2018-04-02 22:08:13.182242726 +0000 UTC m=+11.818467905: Error result for containerd (took 342.933823ms): exit status 2
2018-04-02 22:08:13.647036306 +0000 UTC m=+12.283261410: Error result for rkt (took 463.21281ms): exit status 2
2018-04-02 22:08:13.998557104 +0000 UTC m=+12.634782235: Error result for cni (took 349.923661ms): exit status 2
2018-04-02 22:08:14.469711411 +0000 UTC m=+13.105936590: Error result for envoy (took 469.577791ms): exit status 2
2018-04-02 22:08:14.841630225 +0000 UTC m=+13.477855393: Error result for jaeger (took 370.007321ms): exit status 2
2018-04-02 22:08:15.204554059 +0000 UTC m=+13.840779211: Error result for notary (took 361.301735ms): exit status 2
2018-04-02 22:08:15.584217311 +0000 UTC m=+14.220442469: Error result for tuf (took 377.891071ms): exit status 2
2018-04-02 22:08:15.924899789 +0000 UTC m=+14.561124943: Error result for rook (took 338.964867ms): exit status 2
2018-04-02 22:08:16.303148291 +0000 UTC m=+14.939373423: Error result for vitess (took 376.427552ms): exit status 2
2018-04-02 22:08:16.762590379 +0000 UTC m=+15.398815525: Error result for nats (took 457.723432ms): exit status 2
2018-04-02 22:08:17.119858223 +0000 UTC m=+15.756083331: Error result for opa (took 355.506319ms): exit status 2
2018-04-02 22:08:17.456413243 +0000 UTC m=+16.092638422: Error result for spiffe (took 334.511306ms): exit status 2
2018-04-02 22:08:17.97077846 +0000 UTC m=+16.607003588: Error result for spire (took 512.414653ms): exit status 2
2018-04-02 22:08:18.347383761 +0000 UTC m=+16.983608940: Error result for opencontainers (took 375.141599ms): exit status 2
2018-04-02 22:08:18.70348418 +0000 UTC m=+17.339709359: Error result for all (took 354.111084ms): exit status 2
2018-04-02 23:08:13.105539805 +0000 UTC m=+11.222248929: Error result for kubernetes (took 360.294576ms): exit status 2
2018-04-02 23:08:13.59999672 +0000 UTC m=+11.716705879: Error result for prometheus (took 493.1028ms): exit status 2
2018-04-02 23:08:14.234426438 +0000 UTC m=+12.351135617: Error result for opentracing (took 632.890606ms): exit status 2
2018-04-02 23:08:14.735291498 +0000 UTC m=+12.852000664: Error result for fluentd (took 498.822278ms): exit status 2
2018-04-02 23:08:15.12890614 +0000 UTC m=+13.245615256: Error result for linkerd (took 391.993267ms): exit status 2
2018-04-02 23:08:15.519639599 +0000 UTC m=+13.636348768: Error result for grpc (took 388.64327ms): exit status 2
2018-04-02 23:08:15.866621656 +0000 UTC m=+13.983330849: Error result for coredns (took 345.11328ms): exit status 2
2018-04-02 23:08:16.227526216 +0000 UTC m=+14.344235395: Error result for containerd (took 359.179007ms): exit status 2
2018-04-02 23:08:16.735293608 +0000 UTC m=+14.852002751: Error result for rkt (took 505.872077ms): exit status 2
2018-04-02 23:08:17.101542527 +0000 UTC m=+15.218251713: Error result for cni (took 364.719611ms): exit status 2
2018-04-02 23:08:17.461434622 +0000 UTC m=+15.578143791: Error result for envoy (took 358.082206ms): exit status 2
2018-04-02 23:08:17.819105982 +0000 UTC m=+15.935815151: Error result for jaeger (took 355.960432ms): exit status 2
2018-04-02 23:08:18.183419031 +0000 UTC m=+16.300128227: Error result for notary (took 362.512787ms): exit status 2
2018-04-02 23:08:18.550313173 +0000 UTC m=+16.667022279: Error result for tuf (took 365.162923ms): exit status 2
2018-04-02 23:08:18.894384159 +0000 UTC m=+17.011093365: Error result for rook (took 342.476048ms): exit status 2
2018-04-02 23:08:19.282407403 +0000 UTC m=+17.399116547: Error result for vitess (took 386.492975ms): exit status 2
2018-04-02 23:08:19.64927369 +0000 UTC m=+17.765983037: Error result for nats (took 365.157072ms): exit status 2
2018-04-02 23:08:20.0345519 +0000 UTC m=+18.151261106: Error result for opa (took 383.519967ms): exit status 2
2018-04-02 23:08:20.342107689 +0000 UTC m=+18.458816841: Error result for spiffe (took 306.04459ms): exit status 2
2018-04-02 23:08:20.740748703 +0000 UTC m=+18.857457829: Error result for spire (took 396.950669ms): exit status 2
2018-04-02 23:08:21.059058786 +0000 UTC m=+19.175767919: Error result for opencontainers (took 317.045436ms): exit status 2
2018-04-02 23:08:21.395844123 +0000 UTC m=+19.512553306: Error result for all (took 335.581643ms): exit status 2
```

All those errors are of the same type, this is one of them (full info that I've caught in logs):
```
2018-04-02 23:08:21 all/gha2db: Working on 2018-04-02 22:00:00 +0000 UTC
2018-04-02 23:08:21 all/gha2db: 2018-04-02 22:00:00 +0000 UTC: Error http.Get:
Get https://data.gharchive.org/2018-04-02-22.json.gz: x509: certificate is valid for *.storage.googleapis.com, *.appspot.com.storage.googleapis.com, *.commondatastorage.googleapis.com, *.content-stora
2018-04-02 23:08:21 all/gha2db: Error(time=2018-04-02 23:08:21.38040275 +0000 UTC m=+0.267522530):
Error: 'Get https://data.gharchive.org/2018-04-02-22.json.gz: x509: certificate is valid for *.storage.googleapis.com, *.appspot.com.storage.googleapis.com, *.commondatastorage.googleapis.com, *.conte
Stacktrace:
goroutine 9 [running]:
runtime/debug.Stack(0xc4204fb6e0, 0xc4203dcc80, 0x253)
  /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
devstats.FatalOnError(0x873460, 0xc4204fb6e0, 0x71a4d2, 0x17)
  /data/go/src/devstats/error.go:24 +0x301
main.getGHAJSON(0xc4200a8240, 0xc420061c00, 0x0, 0xed2549ee0, 0x8ab7c0, 0xc4200aeea0, 0xc4200aeed0)
  /data/go/src/devstats/cmd/gha2db/gha2db.go:1398 +0x493
created by main.gha2db
  /data/go/src/devstats/cmd/gha2db/gha2db.go:1538 +0x9f0


2018-04-02 23:08:21 all/gha2db_sync: STDERR:
2018-04-02 22:00:00 +0000 UTC: Error http.Get:
Get https://data.gharchive.org/2018-04-02-22.json.gz: x509: certificate is valid for *.storage.googleapis.com, *.appspot.com.storage.googleapis.com, *.commondatastorage.googleapis.com, *.content-stora
Error(time=2018-04-02 23:08:21.38040275 +0000 UTC m=+0.267522530):
Error: 'Get https://data.gharchive.org/2018-04-02-22.json.gz: x509: certificate is valid for *.storage.googleapis.com, *.appspot.com.storage.googleapis.com, *.commondatastorage.googleapis.com, *.conte
Stacktrace:
panic: stacktrace

goroutine 9 [running]:
devstats.FatalOnError(0x873460, 0xc4204fb6e0, 0x71a4d2, 0x17)
  /data/go/src/devstats/error.go:26 +0x5a3
main.getGHAJSON(0xc4200a8240, 0xc420061c00, 0x0, 0xed2549ee0, 0x8ab7c0, 0xc4200aeea0, 0xc4200aeed0)
  /data/go/src/devstats/cmd/gha2db/gha2db.go:1398 +0x493
created by main.gha2db
  /data/go/src/devstats/cmd/gha2db/gha2db.go:1538 +0x9f0

2018-04-02 23:08:21 all/gha2db_sync: Command, arguments, environment:
[gha2db 2018-04-02 20 2018-04-02 23 kubernetes,kubernetes-client,kubernetes-incubator,kubernetes-helm,prometheus,opentracing,fluent,linkerd,grpc,coredns,containerd,rkt,containernetworking,envoyproxy,j
map[]
Command and arguments:
[gha2db 2018-04-02 20 2018-04-02 23 kubernetes,kubernetes-client,kubernetes-incubator,kubernetes-helm,prometheus,opentracing,fluent,linkerd,grpc,coredns,containerd,rkt,containernetworking,envoyproxy,j
map[]
2018-04-02 23:08:21 all/gha2db_sync: Error(time=2018-04-02 23:08:21.388317622 +0000 UTC m=+0.326547495):
Error: 'exit status 2'
Stacktrace:
goroutine 1 [running]:
runtime/debug.Stack(0xc4201ce940, 0xc4201cc8c1, 0xd)
  /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
devstats.FatalOnError(0x8d2700, 0xc4201ce940, 0x7, 0x7)
  /data/go/src/devstats/error.go:24 +0x301
devstats.ExecCommand(0xc42014c000, 0xc4201e23f0, 0x7, 0x7, 0x0, 0x75a5d1, 0x6, 0x0, 0xc9348766666822b0)
  /data/go/src/devstats/exec.go:143 +0xc55
main.sync(0xc42014c000, 0xc420184ed0, 0x1, 0x1)
  /data/go/src/devstats/cmd/gha2db_sync/gha2db_sync.go:336 +0x3562
main.main()
  /data/go/src/devstats/cmd/gha2db_sync/gha2db_sync.go:659 +0xc7
```

**Comment by lukaszgryglicki** [comment]
cc @dankohn

**Comment by igrigorik** [comment]
Doh, my bad, missed this as part of https://github.com/igrigorik/gharchive.org/issues/178. 

Updated the upload cron job (https://github.com/igrigorik/gharchive.org/commit/7ada8644d842e97f5bf90289edf47546d9dc03f4) and backfilled the data in the new bucket. I believe everything should be a-OK now.. let me know if otherwise.

**Comment by lukaszgryglicki** [comment]
All auto-healed once it got the data. Thanks.
